import requests
import json

# Konfigurace
channel_name = "test_cloos2"      # Název kanálu
device_name = "MyNewDevice2"       # Název zařízení
tag_name = "MyNewTag"             # Název nového tagu

# Endpoint pro vytvoření tagu
url = f"http://127.0.0.1:57412/config/v1/project/channels/{channel_name}/devices/{device_name}/tags"

# Přihlašovací údaje
username = "Administrator"
password = "Kepserver_test1"
headers = {"Content-Type": "application/json"}

# JSON konfigurace pro tag – bezpečnostní parametry zde NEPOUŽÍVEJTE
payload = {
	"common.ALLTYPES_NAME": "test2",
	"common.ALLTYPES_DESCRIPTION": "description for testing tag",
	"servermain.TAG_ADDRESS": "ns=3;s=test_cloos2.MyNewDevice2.test1",
	"servermain.TAG_DATA_TYPE": -1,
	"servermain.TAG_READ_WRITE_ACCESS": 1,
	"servermain.TAG_SCAN_RATE_MILLISECONDS": 100,
	"servermain.TAG_AUTOGENERATED": False,
	"servermain.TAG_SCALING_TYPE": 0,
	"servermain.TAG_SCALING_RAW_LOW": 0,
	"servermain.TAG_SCALING_RAW_HIGH": 1000,
	"servermain.TAG_SCALING_SCALED_DATA_TYPE": 9,
	"servermain.TAG_SCALING_SCALED_LOW": 0,
	"servermain.TAG_SCALING_SCALED_HIGH": 1000,
	"servermain.TAG_SCALING_CLAMP_LOW": False,
	"servermain.TAG_SCALING_CLAMP_HIGH": False,
	"servermain.TAG_SCALING_NEGATE_VALUE": False,
	"servermain.TAG_SCALING_UNITS": ""
}

# Odeslání požadavku na vytvoření tagu
response = requests.post(
    url,
    headers=headers,
    data=json.dumps(payload),
    auth=(username, password)
)

# Vyhodnocení výsledku
if response.status_code == 201:
    print(f"✅ Tag '{tag_name}' byl úspěšně vytvořen v zařízení '{device_name}'!")
else:
    print(f"❌ Chyba při vytváření tagu: {response.status_code}")
    print(response.text)
