OPC_DA_Client = {
    "PROJECT_ID": 3149364503,
    "common.ALLTYPES_NAME": "ABBRobot",
    "common.ALLTYPES_DESCRIPTION": "ABB Robot",
    "servermain.MULTIPLE_TYPES_DEVICE_DRIVER": "OPC DA Client",
    "servermain.CHANNEL_DIAGNOSTICS_CAPTURE": False,
    "servermain.CHANNEL_UNIQUE_ID": 1187912584,
    "servermain.CHANNEL_STATIC_TAG_COUNT": 3090,
    "servermain.CHANNEL_WRITE_OPTIMIZATIONS_METHOD": 2,
    "servermain.CHANNEL_WRITE_OPTIMIZATIONS_DUTY_CYCLE": 10,
    "servermain.CHANNEL_NON_NORMALIZED_FLOATING_POINT_HANDLING": 1,
    "opcdaclient.CHANNEL_PROG_ID": "ABB.IRC5.OPC.Server.DA",
    "opcdaclient.CHANNEL_REMOTE_MACHINE_NAME": "",
    "opcdaclient.CHANNEL_CONNECTION_TYPE": 21,
    "opcdaclient.CHANNEL_FAILED_CONNECTION_RETRY_INTERVAL_SEC": 5,
    "opcdaclient.CHANNEL_SERVER_STATUS_QUERY_INTERVAL_SEC": 5
}

Allen_Bradley_ControlLogix_Ethernet = {
    "PROJECT_ID": 3149364503,
    "common.ALLTYPES_NAME": "CAIRO_ST3_Filling",
    "common.ALLTYPES_DESCRIPTION": "CAIRO",
    "servermain.MULTIPLE_TYPES_DEVICE_DRIVER": "Allen-Bradley ControlLogix Ethernet",
    "servermain.CHANNEL_DIAGNOSTICS_CAPTURE": False,
    "servermain.CHANNEL_UNIQUE_ID": 1007250381,
    "servermain.CHANNEL_STATIC_TAG_COUNT": 14218,
    "servermain.CHANNEL_ETHERNET_COMMUNICATIONS_NETWORK_ADAPTER_STRING": "",
    "servermain.CHANNEL_WRITE_OPTIMIZATIONS_METHOD": 2,
    "servermain.CHANNEL_WRITE_OPTIMIZATIONS_DUTY_CYCLE": 10,
    "servermain.CHANNEL_NON_NORMALIZED_FLOATING_POINT_HANDLING": 0
}

Torque_Tool_Ethernet = {
    "PROJECT_ID": 3149364503,
    "common.ALLTYPES_NAME": "MES AC_CWL_ASSY_PF6K",
    "common.ALLTYPES_DESCRIPTION": "",
    "servermain.MULTIPLE_TYPES_DEVICE_DRIVER": "Torque Tool Ethernet",
    "servermain.CHANNEL_DIAGNOSTICS_CAPTURE": False,
    "servermain.CHANNEL_UNIQUE_ID": 3105381317,
    "servermain.CHANNEL_STATIC_TAG_COUNT": 46,
    "servermain.CHANNEL_ETHERNET_COMMUNICATIONS_NETWORK_ADAPTER_STRING": "",
    "servermain.CHANNEL_WRITE_OPTIMIZATIONS_METHOD": 2,
    "servermain.CHANNEL_WRITE_OPTIMIZATIONS_DUTY_CYCLE": 10,
    "servermain.CHANNEL_NON_NORMALIZED_FLOATING_POINT_HANDLING": 1
}

ODBC_Client = {
    "PROJECT_ID": 3149364503,
    "common.ALLTYPES_NAME": "LaserCutting",
    "common.ALLTYPES_DESCRIPTION": "",
    "servermain.MULTIPLE_TYPES_DEVICE_DRIVER": "ODBC Client",
    "servermain.CHANNEL_DIAGNOSTICS_CAPTURE": False,
    "servermain.CHANNEL_UNIQUE_ID": 3434978842,
    "servermain.CHANNEL_STATIC_TAG_COUNT": 136,
    "servermain.CHANNEL_WRITE_OPTIMIZATIONS_METHOD": 2,
    "servermain.CHANNEL_WRITE_OPTIMIZATIONS_DUTY_CYCLE": 10,
    "servermain.CHANNEL_NON_NORMALIZED_FLOATING_POINT_HANDLING": 1,
    "odbcclient.CHANNEL_DATA_SOURCE_NAME": "LaserCutting_DB",
    "odbcclient.CHANNEL_DATA_SOURCE_USERNAME": "HGDS",
    "odbcclient.CHANNEL_DATA_SOURCE_PASSWORD": "81ec52e3985bcdaf9e6a4bec08e3237d8940f1c6cfbc4c4028a66c80c4d1a8e2ade2f6169bdce8dd",
    "odbcclient.CHANNEL_LOGIN_TIMEOUT_S": 5
}

OPC_UA_Client = {
    "PROJECT_ID": 3149364503,
    "common.ALLTYPES_NAME": "s71500",
    "common.ALLTYPES_DESCRIPTION": "",
    "servermain.MULTIPLE_TYPES_DEVICE_DRIVER": "OPC UA Client",
    "servermain.CHANNEL_DIAGNOSTICS_CAPTURE": False,
    "servermain.CHANNEL_UNIQUE_ID": 647913883,
    "servermain.CHANNEL_STATIC_TAG_COUNT": 364,
    "servermain.CHANNEL_WRITE_OPTIMIZATIONS_METHOD": 2,
    "servermain.CHANNEL_WRITE_OPTIMIZATIONS_DUTY_CYCLE": 10,
    "servermain.CHANNEL_NON_NORMALIZED_FLOATING_POINT_HANDLING": 1,
    "opcuaclient.CHANNEL_UA_SERVER_ENDPOINT_URL": "opc.tcp://10.52.33.43:4840",
    "opcuaclient.CHANNEL_UA_SERVER_SECURITY_POLICY": 0,
    "opcuaclient.CHANNEL_UA_SERVER_MESSAGE_MODE": 1,
    "opcuaclient.CHANNEL_UA_SESSION_CONNECT_TIMEOUT_SECONDS": 30,
    "opcuaclient.CHANNEL_UA_SESSION_TIMEOUT_INACTIVE_MINUTES": 20,
    "opcuaclient.CHANNEL_UA_SESSION_RENEWAL_INTERVAL_MINUTES": 60,
    "opcuaclient.CHANNEL_UA_SESSION_FAILED_CONNCTION_RETRY_INTERVAL_SECONDS": 5,
    "opcuaclient.CHANNEL_UA_SESSION_WATCHDOG_TIMEOUT": 5,
    "opcuaclient.CHANNEL_AUTHENTICATION_USERNAME": "",
    "opcuaclient.CHANNEL_AUTHENTICATION_PASSWORD": ""
}

