OPC_DA_Client_device = {
	"PROJECT_ID": 3149364503,
	"common.ALLTYPES_NAME": "Device1",
	"common.ALLTYPES_DESCRIPTION": "",
	"servermain.MULTIPLE_TYPES_DEVICE_DRIVER": "OPC DA Client",
	"servermain.DEVICE_MODEL": 0,
	"servermain.DEVICE_UNIQUE_ID": 55950100,
	"servermain.DEVICE_CHANNEL_ASSIGNMENT": "ABBRobot",
	"servermain.DEVICE_DATA_COLLECTION": False,
	"servermain.DEVICE_SIMULATED": False,
	"servermain.DEVICE_STATIC_TAG_COUNT": 1525,
	"servermain.DEVICE_SCAN_MODE": 0,
	"servermain.DEVICE_SCAN_MODE_RATE_MS": 1000,
	"servermain.DEVICE_SCAN_MODE_PROVIDE_INITIAL_UPDATES_FROM_CACHE": False,
	"opcdaclient.DEVICE_GROUP_NAME": "",
	"opcdaclient.DEVICE_UPDATE_MODE": 0,
	"opcdaclient.DEVICE_UPDATE_POLL_RATE_MS": 1000,
	"opcdaclient.DEVICE_PERCENT_DEADBAND": 0,
	"opcdaclient.DEVICE_LANGUAGE_ID": 1033,
	"opcdaclient.DEVICE_WRITE_METHOD": 0,
	"opcdaclient.DEVICE_READ_METHOD": 0,
	"opcdaclient.DEVICE_MAX_ITEMS_PER_READ": 512,
	"opcdaclient.DEVICE_MAX_ITEMS_PER_WRITE": 512,
	"opcdaclient.DEVICE_READ_TIMEOUT_MS": 1000,
	"opcdaclient.DEVICE_WRITE_TIMEOUT_MS": 1000,
	"opcdaclient.DEVICE_READ_AFTER_WRITE": True,
	"opcdaclient.DEVICE_WATCHDOG": False,
	"opcdaclient.DEVICE_ITEM_ID_OF_WATCHDOG_TAG": "",
	"opcdaclient.DEVICE_MISSED_UPDATES_BEFORE_RECONNECT": 3,
	"opcdaclient.DEVICE_IMPORT_ITEMS": [
		6,
		0,
		0,
		0,
		223,
		238,
		176,
		9,
		224,
		230,
		64,
		78,
		33,
		160,
		28,
		255,
		170,
		191,
		201,
		31,
		1,
		0,
		0,
		0,
		0,
		0
	]
}

Allen_Bradley_ControlLogix_Ethernet_device = {
	"PROJECT_ID": 3149364503,
	"common.ALLTYPES_NAME": "Device",
	"common.ALLTYPES_DESCRIPTION": "ST3",
	"servermain.MULTIPLE_TYPES_DEVICE_DRIVER": "Allen-Bradley ControlLogix Ethernet",
	"servermain.DEVICE_MODEL": 1,
	"servermain.DEVICE_UNIQUE_ID": 344354181,
	"servermain.DEVICE_CHANNEL_ASSIGNMENT": "CAIRO_ST3_Filling",
	"servermain.DEVICE_ID_FORMAT": 0,
	"servermain.DEVICE_ID_STRING": "<10.52.32.67>,1,0",
	"servermain.DEVICE_ID_HEXADECIMAL": 0,
	"servermain.DEVICE_ID_DECIMAL": 0,
	"servermain.DEVICE_ID_OCTAL": 0,
	"servermain.DEVICE_DATA_COLLECTION": True,
	"servermain.DEVICE_SIMULATED": False,
	"servermain.DEVICE_STATIC_TAG_COUNT": 14218,
	"servermain.DEVICE_SCAN_MODE": 0,
	"servermain.DEVICE_SCAN_MODE_RATE_MS": 1000,
	"servermain.DEVICE_SCAN_MODE_PROVIDE_INITIAL_UPDATES_FROM_CACHE": False,
	"servermain.DEVICE_CONNECTION_TIMEOUT_SECONDS": 3,
	"servermain.DEVICE_REQUEST_TIMEOUT_MILLISECONDS": 1000,
	"servermain.DEVICE_RETRY_ATTEMPTS": 3,
	"servermain.DEVICE_INTER_REQUEST_DELAY_MILLISECONDS": 0,
	"servermain.DEVICE_AUTO_DEMOTION_ENABLE_ON_COMMUNICATIONS_FAILURES": False,
	"servermain.DEVICE_AUTO_DEMOTION_DEMOTE_AFTER_SUCCESSIVE_TIMEOUTS": 3,
	"servermain.DEVICE_AUTO_DEMOTION_PERIOD_MS": 10000,
	"servermain.DEVICE_AUTO_DEMOTION_DISCARD_WRITES": False,
	"servermain.DEVICE_TAG_GENERATION_ON_STARTUP": 0,
	"servermain.DEVICE_TAG_GENERATION_DUPLICATE_HANDLING": 0,
	"servermain.DEVICE_TAG_GENERATION_GROUP": "",
	"servermain.DEVICE_TAG_GENERATION_ALLOW_SUB_GROUPS": True,
	"controllogix_ethernet.DEVICE_PORT_NUMBER": 44818,
	"controllogix_ethernet.DEVICE_CONNECTION_SIZE_BYTES": 500,
	"controllogix_ethernet.DEVICE_INACTIVITY_WATCHDOG_SECONDS": 32,
	"controllogix_ethernet.DEVICE_ARRAY_BLOCK_SIZE_ELEMENTS": 120,
	"controllogix_ethernet.DEVICE_PROTOCOL_MODE": 0,
	"controllogix_ethernet.DEVICE_ONLINE_EDITS": True,
	"controllogix_ethernet.DEVICE_OFFLINE_EDITS": True,
	"controllogix_ethernet.DEVICE_AUTOMATICALLY_READ_STRING_LENGTH": True,
	"controllogix_ethernet.DEVICE_DEFAULT_DATA_TYPE": -1,
	"controllogix_ethernet.DEVICE_ENABLE_PERFORMANCE_STATISTICS": False,
	"controllogix_ethernet.DEVICE_DATABASE_IMPORT_METHOD": 0,
	"controllogix_ethernet.DEVICE_TAG_IMPORT_FILE": "*.l5k",
	"controllogix_ethernet.DEVICE_DISPLAY_DESCRIPTIONS": True,
	"controllogix_ethernet.DEVICE_LIMIT_TAG_NAMES": False,
	"controllogix_ethernet.DEVICE_TAG_HIERARCHY": 1,
	"controllogix_ethernet.DEVICE_IMPOSE_ARRAY_ELEMENT_COUNT_LIMIT": False,
	"controllogix_ethernet.DEVICE_ARRAY_ELEMENT_COUNT_LIMIT": 2000,
	"controllogix_ethernet.DEVICE_CL_ENET_PORT_NUMBER": 44818,
	"controllogix_ethernet.DEVICE_REQUEST_SIZE": 232,
	"controllogix_ethernet.DEVICE_PERFORM_BLOCK_WRITES": False,
	"controllogix_ethernet.DEVICE_SLOT_CONFIGURATION": {
		"controllogix_ethernet.DEVICE_SLOT_CONFIGURATION_MODULE": [
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255,
			255
		],
		"controllogix_ethernet.DEVICE_SLOT_CONFIGURATION_INPUT_WORDS": [
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0
		],
		"controllogix_ethernet.DEVICE_SLOT_CONFIGURATION_OUTPUT_WORDS": [
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0,
			0
		]
	},
	"redundancy.DEVICE_SECONDARY_PATH": "",
	"redundancy.DEVICE_OPERATING_MODE": 0,
	"redundancy.DEVICE_MONITOR_ITEM": "",
	"redundancy.DEVICE_MONITOR_ITEM_POLL_INTERVAL": 300,
	"redundancy.DEVICE_FAVOR_PRIMARY": True,
	"redundancy.DEVICE_TRIGGER_ITEM": "",
	"redundancy.DEVICE_TRIGGER_ITEM_SCAN_RATE": 1000,
	"redundancy.DEVICE_TRIGGER_TYPE": 0,
	"redundancy.DEVICE_TRIGGER_OPERATOR": 0,
	"redundancy.DEVICE_TRIGGER_VALUE": "",
	"redundancy.DEVICE_TRIGGER_TIMEOUT": 10000
}

Torque_Tool_Ethernet_device = {
	"PROJECT_ID": 3149364503,
	"common.ALLTYPES_NAME": "CWL_CAL_ST1_2",
	"common.ALLTYPES_DESCRIPTION": "",
	"servermain.MULTIPLE_TYPES_DEVICE_DRIVER": "Torque Tool Ethernet",
	"servermain.DEVICE_MODEL": 0,
	"servermain.DEVICE_UNIQUE_ID": 1464525338,
	"servermain.DEVICE_CHANNEL_ASSIGNMENT": "MES CWL_CAL_ST1_2",
	"servermain.DEVICE_ID_FORMAT": 0,
	"servermain.DEVICE_ID_STRING": "10.52.108.16",
	"servermain.DEVICE_ID_HEXADECIMAL": 0,
	"servermain.DEVICE_ID_DECIMAL": 0,
	"servermain.DEVICE_ID_OCTAL": 0,
	"servermain.DEVICE_DATA_COLLECTION": True,
	"servermain.DEVICE_SIMULATED": False,
	"servermain.DEVICE_STATIC_TAG_COUNT": 46,
	"servermain.DEVICE_SCAN_MODE": 0,
	"servermain.DEVICE_SCAN_MODE_RATE_MS": 1000,
	"servermain.DEVICE_SCAN_MODE_PROVIDE_INITIAL_UPDATES_FROM_CACHE": False,
	"servermain.DEVICE_CONNECTION_TIMEOUT_SECONDS": 3,
	"servermain.DEVICE_REQUEST_TIMEOUT_MILLISECONDS": 1000,
	"servermain.DEVICE_RETRY_ATTEMPTS": 3,
	"torque_tool_ethernet.DEVICE_PORT_NUMBER": 4552,
	"torque_tool_ethernet.DEVICE_SET_ERROR_FOR_DNR": False,
	"torque_tool_ethernet.DEVICE_POLL_TIME_SEC": 10,
	"torque_tool_ethernet.DEVICE_REPLY_TIMEOUT_MS": 1000,
	"torque_tool_ethernet.DEVICE_FAIL_AFTER": 3,
	"torque_tool_ethernet.DEVICE_ALARM_REV": 0,
	"torque_tool_ethernet.DEVICE_COMMUNICATION_REV": 0,
	"torque_tool_ethernet.DEVICE_JOB_DATA": 0,
	"torque_tool_ethernet.DEVICE_JOB_INFO": 0,
	"torque_tool_ethernet.DEVICE_JOB_STATE": 0,
	"torque_tool_ethernet.DEVICE_LAST_TIGHTENING": 0,
	"torque_tool_ethernet.DEVICE_OLD_TIGHTENING": 0,
	"torque_tool_ethernet.DEVICE_SELECTOR_LIGHTS_REV": 0,
	"torque_tool_ethernet.DEVICE_TOOL_DATA_REV": 0,
	"torque_tool_ethernet.DEVICE_VIN": 0,
	"torque_tool_ethernet.DEVICE_DISABLE_TOOL_ON_LTR": False,
	"torque_tool_ethernet.DEVICE_REVISION_FORMAT": -1,
	"torque_tool_ethernet.DEVICE_USE_GENERIC_SUBSCRIBE": False,
	"torque_tool_ethernet.DEVICE_USE_UNSOLICITED_DATA_PACKING": True,
	"redundancy.DEVICE_SECONDARY_PATH": "",
	"redundancy.DEVICE_OPERATING_MODE": 0,
	"redundancy.DEVICE_MONITOR_ITEM": "",
	"redundancy.DEVICE_MONITOR_ITEM_POLL_INTERVAL": 300,
	"redundancy.DEVICE_FAVOR_PRIMARY": True,
	"redundancy.DEVICE_TRIGGER_ITEM": "",
	"redundancy.DEVICE_TRIGGER_ITEM_SCAN_RATE": 1000,
	"redundancy.DEVICE_TRIGGER_TYPE": 0,
	"redundancy.DEVICE_TRIGGER_OPERATOR": 0,
	"redundancy.DEVICE_TRIGGER_VALUE": "",
	"redundancy.DEVICE_TRIGGER_TIMEOUT": 10000
}

ODBC_Client_device = {
	"PROJECT_ID": 3149364503,
	"common.ALLTYPES_NAME": "Laser1_Alarms",
	"common.ALLTYPES_DESCRIPTION": "Laser 1",
	"servermain.MULTIPLE_TYPES_DEVICE_DRIVER": "ODBC Client",
	"servermain.DEVICE_MODEL": 0,
	"servermain.DEVICE_UNIQUE_ID": 3556483886,
	"servermain.DEVICE_CHANNEL_ASSIGNMENT": "LaserCutting",
	"servermain.DEVICE_ID_FORMAT": 1,
	"servermain.DEVICE_ID_STRING": "0",
	"servermain.DEVICE_ID_HEXADECIMAL": 0,
	"servermain.DEVICE_ID_DECIMAL": 0,
	"servermain.DEVICE_ID_OCTAL": 0,
	"servermain.DEVICE_DATA_COLLECTION": True,
	"servermain.DEVICE_SIMULATED": False,
	"servermain.DEVICE_STATIC_TAG_COUNT": 12,
	"servermain.DEVICE_SCAN_MODE": 0,
	"servermain.DEVICE_SCAN_MODE_RATE_MS": 1000,
	"servermain.DEVICE_SCAN_MODE_PROVIDE_INITIAL_UPDATES_FROM_CACHE": False,
	"servermain.DEVICE_TAG_GENERATION_ON_PROPERTY_CHANGE": False,
	"servermain.DEVICE_TAG_GENERATION_ON_STARTUP": 0,
	"servermain.DEVICE_TAG_GENERATION_DUPLICATE_HANDLING": 0,
	"servermain.DEVICE_TAG_GENERATION_GROUP": "",
	"servermain.DEVICE_TAG_GENERATION_ALLOW_SUB_GROUPS": True,
	"odbcclient.DEVICE_DATA_ACCESS_METHOD": 2,
	"odbcclient.DEVICE_TABLE_SELECTION": "",
	"odbcclient.DEVICE_QUERY": "SELECT alarm.ID as AlarmID, evt.AplzID, alarm.FehlerNr, IsActive, Text, evt.Zeitstempel, MeldungsTyp, Terminal, IsArchiviert, MeldungsGrundID, HpProgName, OriginalMeldungsTyp FROM T1000_V01_V001.dbo.MdeMeldung evt LEFT JOIN T1000_V01_V001.dbo.AktMaschinenAlarm alarm ON evt.ID = alarm.MdeMeldungID WHERE evt.AplzID = '30' ORDER BY Zeitstempel DESC",
	"odbcclient.DEVICE_TRIGGER_COLUMN": "",
	"odbcclient.DEVICE_STORED_PROCEDURE_SELECTION": "",
	"odbcclient.DEVICE_STORED_PROCEDURE_CLEAR_INPUTS": False,
	"odbcclient.DEVICE_STORED_PROCEDURE_REINITIALIZE": True,
	"odbcclient.DEVICE_SET_WRITE_ACCESS_FOR_IMPORTED_TAGS": False,
	"odbcclient.DEVICE_COLUMN_SELECTION": "",
	"odbcclient.DEVICE_MAXIMUM_RECORDS_TO_IMPORT": 0,
	"odbcclient.DEVICE_ENABLE_QUERY_INTERVAL": True,
	"odbcclient.DEVICE_QUERY_INTERVAL": 250
}

OPC_UA_Client_device = {
	"PROJECT_ID": 3149364503,
	"common.ALLTYPES_NAME": "1500",
	"common.ALLTYPES_DESCRIPTION": "",
	"servermain.MULTIPLE_TYPES_DEVICE_DRIVER": "OPC UA Client",
	"servermain.DEVICE_MODEL": 0,
	"servermain.DEVICE_UNIQUE_ID": 186814417,
	"servermain.DEVICE_CHANNEL_ASSIGNMENT": "s71500",
	"servermain.DEVICE_DATA_COLLECTION": True,
	"servermain.DEVICE_SIMULATED": False,
	"servermain.DEVICE_STATIC_TAG_COUNT": 364,
	"servermain.DEVICE_SCAN_MODE": 0,
	"servermain.DEVICE_SCAN_MODE_RATE_MS": 1000,
	"servermain.DEVICE_SCAN_MODE_PROVIDE_INITIAL_UPDATES_FROM_CACHE": False,
	"opcuaclient.DEVICE_SUBSCRIPTION_PUBLISHING_INTERVAL_MILLISECONDS": 1000,
	"opcuaclient.DEVICE_SUBSCRIPTION_MAX_NOTIFICATIONS_PER_PUBLISH": 0,
	"opcuaclient.DEVICE_SUBSCRIPTION_UPDATE_MODE": 0,
	"opcuaclient.DEVICE_SUBSCRIPTION_REGISTERED_READWRITE": True,
	"opcuaclient.DEVICE_MAX_ITEMS_PER_READ": 512,
	"opcuaclient.DEVICE_MAX_ITEMS_PER_WRITE": 512,
	"opcuaclient.DEVICE_READ_TIMEOUT_MS": 1000,
	"opcuaclient.DEVICE_WRITE_TIMEOUT_MS": 1000,
	"opcuaclient.DEVICE_READ_AFTER_WRITE": True,
	"opcuaclient.DEVICE_INITIAL_TIMEOUT_MS": 5000,
	"opcuaclient.DEVICE_CONNECTION_LIFETIME_COUNT": 60,
	"opcuaclient.DEVICE_CONNECTION_MAX_KEEP_ALIVE": 5,
	"opcuaclient.DEVICE_CONNECTION_PRIORITY": 0,
	"opcuaclient.DEVICE_MONITORED_ITEMS_SAMPLE_INTERVAL_MILLISECONDS": 500,
	"opcuaclient.DEVICE_MONITORED_ITEMS_QUEUE_SIZE": 1,
	"opcuaclient.DEVICE_MONITORED_ITEMS_DISCARD_OLDEST": True,
	"opcuaclient.DEVICE_MONITORED_ITEMS_DEADBAND_TYPE": 0,
	"opcuaclient.DEVICE_MONITORED_ITEMS_DEADBAND_VALUE": 0,
	"opcuaclient.DEVICE_MONITORED_ITEMS_SELECT_IMPORT": [
		6,
		0,
		0,
		0,
		223,
		238,
		176,
		9,
		224,
		230,
		64,
		78,
		33,
		160,
		28,
		255,
		170,
		191,
		201,
		31,
		1,
		0,
		0,
		0,
		0,
		0
	],
	"redundancy.DEVICE_SECONDARY_PATH": "",
	"redundancy.DEVICE_OPERATING_MODE": 0,
	"redundancy.DEVICE_MONITOR_ITEM": "",
	"redundancy.DEVICE_MONITOR_ITEM_POLL_INTERVAL": 300,
	"redundancy.DEVICE_FAVOR_PRIMARY": True,
	"redundancy.DEVICE_TRIGGER_ITEM": "",
	"redundancy.DEVICE_TRIGGER_ITEM_SCAN_RATE": 1000,
	"redundancy.DEVICE_TRIGGER_TYPE": 0,
	"redundancy.DEVICE_TRIGGER_OPERATOR": 0,
	"redundancy.DEVICE_TRIGGER_VALUE": "",
	"redundancy.DEVICE_TRIGGER_TIMEOUT": 10000
}
